[#946] -  Reimplementación de unit tests para BioSummaryCardComponent
cuentoneta/cuentoneta pull request #1031
Opened 2024-09-25 02:13 UTC by dylanson25

- [x] Usar `toBeInTheDocument` en lugar de `toBeTruthy`.
 - [x] Cambiar la definición de la función `xdescribe` en `describe` antes de crear la pull request vinculada a este issue.
 
Como no incluí la validación del Nombre del autor y la biografía; Agregue una validación de que estuviera un fragmento de la biografía

2024-09-25 17:01 UTC, ErikGIovani requested changes

2024-09-25 17:01 UTC, ErikGIovani commented on src/app/components/bio-summary-card/bio-summary-card.component.spec.ts
Con estos test podemos testear lo que te comentaba, el primero busca el country que se encuentra en el `span` y el segundo el country del `alt` de la imagen:

```js
const country = storyMock.author.nationality.country;
const countryRegex = new RegExp(`\\b${country}\\b`, 'i');

describe('BioSummaryCardComponent', () => {
	it('should render the component', async () => {
		const { container } = await render(BioSummaryCardComponent, {
			inputs: { story: storyMock },
		});

		expect(container).toBeInTheDocument();
	});

	it('should display the country', async () => {
		await render(BioSummaryCardComponent, {
			inputs: {
				story: storyMock,
			},
		});

		expect(screen.getAllByText(countryRegex)).toHaveLength(1);
	});

	it('should display the country image text', async () => {
		await render(BioSummaryCardComponent, {
			inputs: {
				story: storyMock,
			},
		});

		const countryImage = screen.getByRole('img', {
			name: countryRegex,
		});

		expect(countryImage).toBeInTheDocument();
	});
});
```

2024-09-25 18:21 UTC, dylanson25 commented on src/app/components/bio-summary-card/bio-summary-card.component.spec.ts
Okas lo integro

2024-09-25 18:29 UTC, dylanson25 commented on src/app/components/bio-summary-card/bio-summary-card.component.spec.ts
Si no habia pensado en el uso de una expresion regular 😞

2024-09-25 18:51 UTC, dylanson25 commented on src/app/components/bio-summary-card/bio-summary-card.component.spec.ts
El problema del primero es lo que yo mencionaba no esta buscando en el `span` esta regresando todas las coincidencias de `bioSummaryCard` en el caso del `story.mock` ese test sale correcto por que no repite `Francia` _(Country del mock)_ pero si agregas `Francia` en la biografia si te lo marca como error por que ya hay mas de una coincidencia
```js
it('should display the country', async () => {
         await render(BioSummaryCardComponent, {
		inputs: {
			story: storyMock,
		},
	});
	expect(screen.getAllByText(countryRegex)).toHaveLength(1);
});
```
Es un aco que si se puede dar 
![image](https://github.com/user-attachments/assets/e52e6de7-4c4e-4123-a7af-9e559893f288)
cc: @ErikGIovani

2024-09-26 15:39 UTC, dylanson25 commented
### Test del author y country agregados
Para el caso del nombre del author agruegue la bandera **u**  para que los caracteres unicode sean tratados de la manera correcta. 

`const nameRegex = new RegExp(`\\b${name}\\b`, 'iu');`

En este caso la  **ç** causaba error en en el test del nombre
**François Onoff**


cc: @rolivencia

2024-09-26 16:02 UTC, rolivencia approved these changes
Buen trabajo @dylanson25, aprobado. Espero a que @ErikGIovani de su devolución, pero creo que está bien.

Seguimos luego vía Discord la discusión sobre el tema de la performance de esta suite de tests y la de `StoryComponent`.

2024-09-26 17:50 UTC, ErikGIovani approved these changes
Genial 👍

2024-09-26 19:03 UTC, merged