[#435] ajuste de line-height para cumplir con condiciones de accesibilidad
cuentoneta/cuentoneta pull request #615
Opened 2024-02-11 09:48 UTC by Addin

2024-02-12 02:44 UTC, rolivencia commented
Rome, en líneas generales está bien el aporte, pero esto sólo debe aplicar a texto de párrafos multilínea. No aplica al caso de títulos.

2024-02-12 03:03 UTC, rolivencia requested changes
Quedamos a la espera del rollback en los cambios de estilos aplicados a títulos.

2024-02-12 08:56 UTC, Addin commented
Entendido, en cuánto pueda envío los cambios solicitados.

2024-02-12 23:47 UTC, rolivencia approved these changes

2024-02-13 14:01 UTC, merged

2024-02-13 14:01 UTC, rolivencia commented
Aprobado y mergeado. Buen trabajo Rome.

2024-02-13 15:09 UTC, Addin commented
Gracias Ramiro, a seguir 👏 .