[#607] - Clases de tailwind agregadas al story.component
cuentoneta/cuentoneta pull request #633
Opened 2024-02-15 01:44 UTC by ErikGIovani

2024-02-15 11:53 UTC, rolivencia requested changes

2024-02-15 11:53 UTC, rolivencia commented on src/styles.scss
> +// Font size mixins
Los estilos relativos a las fuentes están bien, pero creo que deberían ir en `theme.scss`

2024-02-15 11:53 UTC, rolivencia commented on tailwind.config.js
> +				'source-serift': ['Source Serif Pro', 'sans-serif'],
Hay un typo en el nombre de la fuente: donde dice `source-serift` debería decir `source-serif`

2024-02-15 11:55 UTC, rolivencia commented
Buen detalle el del cambio de `lg` por `xl`, seguramente se me pasó al agregar los viewports al archivo de configuración de Tailwind.

En líneas generales el trabajo está bien, pero dejé algunos comentarios para emprolijar los cambios y también hice mención a un typo en la configuración de Tailwind para las fuentes.

2024-02-15 14:45 UTC, ErikGIovani commented
> Buen detalle el del cambio de `lg` por `xl`, seguramente se me pasó al agregar los viewports al archivo de configuración de Tailwind.
> 
> En líneas generales el trabajo está bien, pero dejé algunos comentarios para emprolijar los cambios y también hice mención a un typo en la configuración de Tailwind para las fuentes.

Gracias por el feedback, cambios agregados 🥳

2024-02-16 14:04 UTC, rolivencia approved these changes
Aprobado. Buen trabajo Erik 🤝

2024-02-16 14:04 UTC, rolivencia commented on src/app/pages/story/story.component.html
> +	<article class="bg-gray-50 p-5 md:p-15 md:rounded-xl">
Apruebo el PR, pero aprovecho a preguntar si en estos casos no podríamos mover estas clases para su aplicación en los archivos .scss

¿Es viable tener algo como esto?

```
article {
  @apply bg-gray-50 p-5 md:p-15 md:rounded-xl;
}
```

2024-02-16 15:12 UTC, ErikGIovani commented on src/app/pages/story/story.component.html
> +	<article class="bg-gray-50 p-5 md:p-15 md:rounded-xl">
Yo recomendaría hacer eso cuando se van a reutilizar en varias partes el mismo conjunto de clases o si el conjunto de clases se vuelve demasiado largo y dificulte su legibilidad 👍

2024-02-16 23:17 UTC, merged