[#621] - queryParams cambiados por params
cuentoneta/cuentoneta pull request #640
Opened 2024-02-17 23:52 UTC by ErikGIovani

2024-02-18 16:20 UTC, rolivencia requested changes
La mayoría de la contribución está bien, pero agregué un par de cosas a ver.

También creo que está faltando el cambiar los links de la nav-bar de la izquierda, dado que no veo que esté incluido el template de ese componente en los cambios.

Sería útil también poder desarrollar un guard para evitar que se rompa la compatibilidad con las rutas escritas en queryParams versus las rutas nuevas.

2024-02-18 16:20 UTC, rolivencia commented on src/app/app.routes.ts
> +		path: `${APP_ROUTE_TREE['STORY']}/:list/:slug`,
El orden de los parámetros debería ser `:slug` y luego `:list`. En algún issue posterior hay que trabajar el tema de resolver la ausencia del parámetro con el nombre de una storylist, y será más sencilla la intervención si la lista es el último parámetro.

2024-02-18 16:20 UTC, rolivencia commented on src/app/components/storylist-card-deck/storylist-card-deck.component.html
> +						? ['/', appRouteTree['STORY'], storylist.slug, publication.story.slug]
Corregir el orden para la navegación también aquí.

2024-02-19 00:58 UTC, ErikGIovani commented
> La mayoría de la contribución está bien, pero agregué un par de cosas a ver.
> 
> También creo que está faltando el cambiar los links de la nav-bar de la izquierda, dado que no veo que esté incluido el template de ese componente en los cambios.
> 
> Sería útil también poder desarrollar un guard para evitar que se rompa la compatibilidad con las rutas escritas en queryParams versus las rutas nuevas. Agregando un guard a las rutas preexistentes, se puede chequear si es que poseen los queryParams correspondientes y a partir de ahí generar una redirección a las rutas nuevas.
> 
> De esa manera evitamos que todos los links ya compartidos en RRSS queden rotos.

Gracias, implementaré los cambios 🥳

2024-02-20 19:16 UTC, rolivencia commented
Agregué algunos cambios mientras sigo viendo cuál es el problema con los URL params y el SSR.

2024-02-27 20:44 UTC, rolivencia commented
Aparentemente el problema estaba causado por un error totalmente ajeno al router, pero que a nivel de SSR puede provocar este tipo de problemas. Vi esta información en un post de StackOverflow e hice el chequeo de arreglar un error relacionado a ngSrc, lo cual casi de manera mágica solucionó el problema con las rutas de múltiples parámetros en SSR.

2024-02-27 22:12 UTC, rolivencia approved these changes

2024-02-28 00:26 UTC, merged