Agregada meta descripción para mejorar el SEO. Corregidos errores de accesibilidad en enlaces en la plantilla de renderizado de publicaciones de storylist
cuentoneta/cuentoneta pull request #654
Opened 2024-03-17 08:50 UTC by Anibal-Alpizar

Antes: 
![image](https://github.com/cuentoneta/cuentoneta/assets/82195641/b4864054-8f1a-4ac2-951f-a7183b1b9da3)

Después: 
![image](https://github.com/cuentoneta/cuentoneta/assets/82195641/8413ac7d-8c77-42f1-83da-625737525a3e)

2024-03-18 14:15 UTC, rolivencia requested changes
Hola @Anibal-Alpizar. Dejé un par de comentarios en mi revisión.

Es necesaria, también, la creación de un issue antes de avanzar hacia adelante con el pull request, para poder cumplir con los requisitos de forma que tenemos a la hora de contribuir el código para la plataforma.

Nos contactamos por aquí (o mejor, por Discord) en caso de que quieras evacuar cualquier duda.

2024-03-18 14:15 UTC, rolivencia commented on src/app/components/storylist-card-deck/storylist-card-deck.component.html
> +			    [routerLink]="['/', appRouteTree['STORY'], publication.story.slug, storylist.slug]"
Este cambio rompería la lógica actual para determinar si se permite o no acceder a un usuario a la lectura de una story desde una tarjeta agregada en un deck. Es necesaria obligatoriamente la validación de `!! publication` y `publication.published` para determinar la navegabilidad hacia una story.

La intención original de esta validación es ocultar cualquier referencia a las historias no publicadas, con lo cual la navegación y la lógica de accesibilidad frente a `attr.href` deben ir de la mano.

2024-03-18 14:15 UTC, rolivencia commented on src/index.html
> +    <meta name="description" content="La Cuentoneta es una iniciativa que busca fomentar y hacer accesible la lectura digital, publicando relatos breves en storylists temáticas. ¡Disfruta, comparte y
La descripción no coincide con los demás textos usados a lo largo del sitio (ver sección "Nosotros" y para la description que usamos en OpenGraph, la cual está un par de líneas más arriba.

![image](https://github.com/cuentoneta/cuentoneta/assets/32349705/dc4ba2b6-bb4c-438a-9ff1-cad6ec6e43ba)

2024-03-18 18:34 UTC, closed without merging

2024-03-18 19:11 UTC, Anibal-Alpizar commented on src/app/components/storylist-card-deck/storylist-card-deck.component.html
> +			    [routerLink]="['/', appRouteTree['STORY'], publication.story.slug, storylist.slug]"
Hola, @rolivencia 
Quería tomarme un momento para agradecerte por tu detallada revisión de mi pull request 
Entiendo completamente la importancia de mantener la lógica de acceso y visibilidad de las historias alineada con la navegación, y aprecio mucho que hayas señalado cómo mi propuesta podría haber afectado eso.

Voy a revisar tu sugerencia y trabajar en una solución que mantenga la integridad de nuestra lógica actual. Si surgen más preguntas o comentarios, no dudes en hacérmelo saber

2024-03-19 18:36 UTC, rolivencia commented on src/app/components/storylist-card-deck/storylist-card-deck.component.html
> +			    [routerLink]="['/', appRouteTree['STORY'], publication.story.slug, storylist.slug]"
Excelente Aníbal. El trabajo sobre el SEO es algo que aún no hemos abordado, por lo que te agradezco que hayas prestado atención al asunto. 

Cuando gustes charlamos para identificar el trabajo que haga falta realizar al respecto y traducirlo en issues.