[#962] Añadida dependencia stylelint y stylelint.yml
cuentoneta/cuentoneta pull request #974
Opened 2024-08-16 16:28 UTC by Addin

- Instalado stylelint y stylelint-config-standard-scss
- Añadido .stylelintrc.json con reglas para SCSS
- Instalado husky y lint-staged
- Configurado hook de pre-commit en package.json
- Agregada configuración de lint-staged para ejecutar stylelint
- Actualizado script de ejecución de Stylelint para usar pnpm, ver [equivalent of npm ci?](https://github.com/orgs/pnpm/discussions/5948)

Soluciona el issue #962.

2024-08-16 17:06 UTC, ErikGIovani requested changes

2024-08-16 17:06 UTC, ErikGIovani commented on .github/workflows/stylelint.yml
> +      - run: pnpm install --frozen-lockfile
Te faltó agregar el flag --ignore-scripts al hacer pnpm install, con eso se solucionaría el problema de projectId de sanity del script postinstall 👍

2024-08-16 17:06 UTC, ErikGIovani commented on package.json
> +	},
Esta configuración no debería de ir aquí, con la finalidad de mantener organizado el package.json y aisladas las configuraciones de cada tool puedes usar el archivo bash llamado pre-commit que se encuentra en la carpeta .husky en la raíz del proyecto 👌

2024-08-16 18:00 UTC, rolivencia commented on .github/workflows/stylelint.yml
> +      - run: pnpm install --frozen-lockfile
No sólo se requiere ese comando, sino también el correr la generación de la configuración de `environment.ts` con el script `set-test-environment.ts`, el cual reemplaza el `set-environment.ts` por defecto en estas etapas del pipeline.

2024-08-16 18:35 UTC, rolivencia requested changes

2024-08-16 18:35 UTC, rolivencia commented on package.json
> +		"stylelint": "^16.8.2",
Agregaría acá también a `stylelint-config-recommended` como plugin

2024-08-16 19:46 UTC, Addin commented on package.json
> +	},
¿Sería solo este? ¿El de lint-staged es correcto?

2024-08-16 19:49 UTC, Addin commented on package.json
> +		"stylelint": "^16.8.2",
Si agrego stylelint-config-recommended, también tendría que extender la configuración en .stylelintrc.json, ¿Correcto? ¿Es válido colocar ambos extends así? { "extends": ["stylelint-config-standard-scss, stylelint-config-recommended"] }

2024-08-16 19:50 UTC, Addin commented on .github/workflows/stylelint.yml
> +      - run: pnpm install --frozen-lockfile
Rami, me perdí en la parte de la configuración de enviroment.ts, podrías reformular la explicación por favor.

2024-08-16 20:01 UTC, ErikGIovani commented on package.json
> +	},
> ¿Sería solo este? ¿El de lint-staged es correcto?

Si, tienes un ejemplo de como agregarlo en un commit previo que se había hecho, pero se decidió por correrlos en actions en lugar de pre-commits.

Y también tiene un ejemplo de como agregar la configuración de lint-stage en un archivo aparte. 

El commit en cuestión: https://github.com/cuentoneta/cuentoneta/commit/78433f31450f48cc24bea2143ef3d7d136f9f569

2024-08-16 23:09 UTC, rolivencia commented on .github/workflows/stylelint.yml
> +      - run: pnpm install --frozen-lockfile
El archivo `environment.ts` se genera dinámicamente en tiempo de compilación, y tiene información estática relativa a las cosasbque mostramos en la landing page.

Para generar esa información se hace una query hacia Sanity al momento del build, lo cual se logra mediante la ejecución del comando  `pnpm run config`, el cual ejecuta un script de nombre `set-environment.ts`. Ese script corre como parte del script de `preinstall`, y es el que está fallando a raíz de que no hay un .env definido en el ambiente de CI/CD.

Por esa razón, como señaló Erik, hay que ejecutar `pnpm install` con el flag de `--ignore-scripts`, a lo que yo te agrego que revises el archivo `testing.yml` para que veas cómo ejecutar el comando que setea el entorno de CI/CD sin requerir un .env

2024-08-16 23:11 UTC, rolivencia commented on package.json
> +	},
El asunto del hook agreguémoslo en un PR posterior @Addin. Da rollback a estos cambios.

2024-08-16 23:13 UTC, rolivencia commented on package.json
> +		"stylelint": "^16.8.2",
Sí, por supuesto. De manera similar a como sucede con `eslint`, acá pueden agregarse varios plugins.

2024-08-17 09:57 UTC, Addin commented on package.json
> +	},
Rollback realizado.

2024-08-17 09:59 UTC, Addin commented on package.json
> +		"stylelint": "^16.8.2",
Añadida la dependencia stylelint-config-recommended.

2024-08-17 10:05 UTC, Addin commented on .github/workflows/stylelint.yml
> +      - run: pnpm install --frozen-lockfile
Hecho los cambios para que se ejecute el archivo de configuración del ambiente de testing.

2024-08-17 11:05 UTC, ErikGIovani requested changes

2024-08-17 11:18 UTC, Addin commented on package.json
> +	"lint-staged": {
Removida la configuración y la dependencia lint-staged.

2024-08-17 11:19 UTC, Addin commented on package.json
> +		"stylelint-config-recommended": "^14.0.1",
Hecho el cambio, stylelint-config-recommended ahora es una dependencia de desarrollo.

2024-08-17 11:20 UTC, Addin commented on package.json
> +		"create-stylelint": "^0.5.0",
Removida la dependencia create-stylelint.

2024-08-17 12:02 UTC, ErikGIovani approved these changes
Good job 🥳🎉🎉

2024-08-17 15:50 UTC, rolivencia commented
Dejé un cambio adicional a realizar a eso le sumo que falta agregar a `package.json` el shorthand para ejecutar el script, el cual según veo debería ser `"stylelint": "pnpm dlx stylelint "**/*.scss""`

2024-08-17 16:06 UTC, rolivencia commented
Agrego otra cosa que no consideré: la corrida de Stylelint está ignorando todos los estilos que están definidos en los archivos `*.component.ts`. Desconozco cómo se puede hacer para correr la herramienta en estos estilos inline.

2024-09-11 23:17 UTC, rolivencia commented
Procedo a cerrar esta PR.

2024-09-11 23:17 UTC, closed without merging