[#897] Añadidos los flags isolatedModules y useDefineForClassFields
cuentoneta/cuentoneta pull request #984
Opened 2024-08-22 10:09 UTC by Addin

- Añadido el flag i[solatedModules](https://www.typescriptlang.org/tsconfig/#isolatedModules).
- Añadido el flag [useDefineForClassFields](https://www.typescriptlang.org/tsconfig/#useDefineForClassFields).
- Soluciona el issue #897.

2024-08-26 13:33 UTC, rolivencia commented
@Addin: por alguna razón la app no corre el linter ni los tests, ¿podés revisarlo?

2024-08-26 13:34 UTC, rolivencia requested changes
No corre el linter ni la suite de tests unitarios. Revisar.

2024-08-26 13:38 UTC, Addin commented
Qué raro che, puede ser que como hay cambios en el CI en los PR's #983 y #981 de algún error en eso.

2024-08-26 21:26 UTC, rolivencia commented
> Qué raro che, puede ser que como hay cambios en el CI en los PR's #983 y #981 de algún error en eso.

No creo que esté relacionado, pude levantar una PR pequeña hoy y pasó sin problemas el CI/CD. El problema es otro.

2024-08-26 21:32 UTC, Addin commented
> > Qué raro che, puede ser que como hay cambios en el CI en los PR's #983 y #981 de algún error en eso.
> 
> No creo que esté relacionado, pude levantar una PR pequeña hoy y pasó sin problemas el CI/CD. El problema es otro.

Mañana lo miro a ver qué puede estar pasando, gracias Ramiro.

2024-08-27 18:14 UTC, Addin commented
Solucionado el problema, al parecer había un conflicto y un par de problemas en el pnpm-lock.yaml por el cambio de versión, ahora funciona bien.

2024-08-28 17:42 UTC, rolivencia approved these changes
Todo perfecto ahora. Aprobado y procedo al merge.

2024-08-28 17:42 UTC, merged